language: node_js
node_js: lts/*
addons:
  apt:
    packages:
      - libgconf-2-4
before_script: npm install -g @angular/cli
script:
- npm install
- ng e2e
- ng build --prod
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: qY5p6E81zUyKnunKms/Lt88fZjMOLFsS5BOGipi0mGHA+wTELB95O1zZN0yxWdHxPCxOZ6qlVtk7gUWQKotJ7zqBDKp4AAiEEFiGFZg5oSD4bb44DnoGNjP6wUSbbEEmq3LrtbEjrrUyxFF91MlCtpydmWNwPOqeQabTd6t0fImPVkaUA8RBbN1e2nGAO0wH61kTrN+e0Dcs0buJKr/uGTPA/t2HcXxLLudh4v53xO0D/fiLrUG2YwWl6aH+pqUKwK7PJhPgHMWgeZPgPGWrtjznurb6gOjznAOfzhcE62pzu/UTPJoQ9RKQZ7ay+OyU5ftCB5l1/jdcISVoASfqozLX4Yvxu/KUmRzYDEmX7k/pciipHVspN3FXAzYA8Kvul/4OAohF3KMvK4xWKr7dDkrMINzQrShnwG+osa1CcKyVJNLYZwKv+bKXzBA40u4qNb4k9/EuYSUCT6nKnKHlsIZhKw7qjymuHCVo7eVF5Cv/VEmzweLgrqGH7vGZy8IC2FwZxDyZ46gEKECbyp/npGmqfWLXxynukRdznzejziH8tWtNWbXb33e3whiy7l0bWqcO15LDXpPTKlFMjv3OPLKNpqrof3fEAw3LFsChocH6sbah9OFeG3kbOVS3OeBnDLAg0SyBbCBKWdXz6eRafLDzWJhyO6VoRO6khBJJS1k=
  on:
    branch: release
    condition: release
